# Generated by Django 3.2.5 on 2021-07-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frase', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacionUsada', models.CharField(choices=[('Instagram', (('Story', 'Story'), ('DM', 'DM'))), ('Tinder', 'Tinder'), ('Bumble', 'Bumble'), ('Twitter', 'Twitter'), ('Otro', 'Otro')], max_length=120, null=True)),
                ('situacionUsada', models.CharField(choices=[('A', 'Abrir Conversación'), ('S', 'Seguir Conversación')], max_length=120, null=True)),
                ('frase', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='frase.frase')),
                ('usuario', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
