# Generated by Django 3.2.5 on 2021-07-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacionUsada', models.CharField(choices=[('Instagram', (('Story', 'Story'), ('DM', 'DM'))), ('Tinder', 'Tinder'), ('Bumble', 'Bumble'), ('Twitter', 'Twitter'), ('Otro', 'Otro')], max_length=120)),
                ('situacionUsada', models.CharField(choices=[('A', 'Abrir Conversación'), ('S', 'Seguir Conversación')], max_length=120)),
            ],
        ),
    ]
