# Generated by Django 3.2.5 on 2021-07-22 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacionUsada', models.CharField(blank=True, choices=[('Instagram', (('Story', 'Story'), ('DM', 'DM'))), ('Tinder', 'Tinder'), ('Bumble', 'Bumble'), ('Twitter', 'Twitter'), ('Otro', 'Otro')], max_length=120, null=True)),
                ('situacionUsada', models.CharField(blank=True, choices=[('A', 'Abrir Conversación'), ('S', 'Seguir Conversación')], max_length=120, null=True)),
                ('frase', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frase.frase')),
                ('usuario', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
