# Generated by Django 3.2.5 on 2021-07-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('username', models.TextField(unique=True)),
                ('score', models.IntegerField(default=0)),
                ('contextF', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='context.context')),
            ],
        ),
    ]
