# Generated by Django 3.2.5 on 2021-07-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('username', models.TextField(unique=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
