# Generated by Django 3.2.5 on 2021-07-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('rendimiento', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='performance.performance')),
            ],
        ),
    ]
