# Generated by Django 3.2.5 on 2021-07-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
