# Generated by Django 3.2.5 on 2021-07-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contextoUsado', models.CharField(max_length=120)),
                ('aplicacionUsada', models.CharField(max_length=120)),
            ],
        ),
    ]
