# Generated by Django 3.2.5 on 2021-07-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='aplicacionUsada',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='contextoUsado',
        ),
    ]
